url: "https://sessions.pub" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Ирландский сейшн в Москве" # the name of your site, e.g. ACME Corp.
timezone: "Europe/Moscow"
lang: "ru"
author: "Самохин Алексей"

plugins:
  - jekyll-feed
