name: Add post

on:
  workflow_dispatch:
    inputs:
      slug:
        description: 'Slug to use in post link'
        required: true
        default: 'zoom'
      date:
        description: 'Year, e.g. 2022-05-03'
        required: true
        default: '2022-05-03'
      time:
        description: 'Time, e.g. 17:00'
        required: true
        default: '17:00'

jobs:
  add_post:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.MY_TOKEN}}
      - uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Run a one-line script
        run: node _scripts/add-zoom-session.js ${{ github.event.inputs.slug }} ${{ github.event.inputs.date }} ${{ github.event.inputs.time }}

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
