name: Send telegram notifications

on:
  workflow_dispatch:
    inputs:
      artifactName:
        description: 'Previous notifications json artifact, e.g. artifact.json'
        required: true
      init:
        description: 'Fresh start (recreate artifact)'
        type: boolean
        default: false

jobs:
  telegram_notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run a one-line script
        run: node _scripts/notify-about-new.js init=${{ github.event.inputs.init }} artifactName=${{ github.event.inputs.artifactName }} token=${{secrets.NOTIFY_TOKEN}} chat_id=${{secrets.NOTIFY_CHAT_ID}}
